name: Jupyter Book Website

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: write
  contents: write
  pull-requests: write

jobs:
  jupyter-book:
    runs-on: ubuntu-latest
    env:
      NPROC: '2'
      JULIA_CACHE: '1'
    container:
      image: ghcr.io/sosiristseng/juliabook:1.8.5.7
      env:
        JULIA_NUM_THREADS: 'auto'
        # Let PythonCall use built-in python
        JULIA_CONDAPKG_BACKEND: 'Null'
        GKSwstype: 100
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Cache Julia dependencies
        uses: actions/cache@v3
        if: ${{ env.JULIA_CACHE != '0'}}
        with:
          path: ~/.julia
          key: ${{ runner.os }}-julia-${{ env.JULIA_CACHE }}-${{ hashFiles('*.toml') }}
          restore-keys: |
            ${{ runner.os }}-julia-${{ env.JULIA_CACHE }}-
      - name: Install Julia dependencies
        run: julia --color=yes --project=@. -e 'import Pkg; Pkg.Registry.update(); Pkg.instantiate(); Pkg.resolve(); Pkg.precompile()'
      - name: Build notebooks with ${{ env.NPROC }} processes
        run: JULIA_PROJECT=@. julia --color=yes -p ${{ env.NPROC }} literate.jl
      - name: Build website
        run: jupyter-book build docs/
      - name: Copy environment files for binder
        env:
          DEST: docs/_build/html/_sources
        run: |
          cp *.txt $DEST || true
          cp Project.toml Manifest.toml $DEST
          cp -R src $DEST
      - name: Deploy Notebooks
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ github.token }}
          publish_dir: docs/_build/html/
          force_orphan: true
  binder:
    needs: jupyter-book
    if: ${{ github.ref == 'refs/heads/main' }}
    uses: sosiristseng/juliabook/.github/workflows/binder.yml@main
    with:
        dir: _sources
        ref: gh-pages
