name: Check markdown links

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *' # Every month
  push:
    branches:
      - main
    paths:
      - '.github/workflows/linkcheck.yml'

env:
  PY_VER: '3.11'

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: out
      - name: Disable code cell execution
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.execute.execute_notebooks = "off"' 'docs/_config.yml'
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PY_VER }}
      - name: Install Jupyter book and check links
        run: pipx run jupyter-book build docs/ --builder linkcheck
