name: Check markdown links

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *' # Every month
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/linkcheck.yml'

jobs:
  linkcheck:
    uses: sosiristseng/juliabook/.github/workflows/lychee.yml@main
